services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: queuenow_app
    ports:
      - "8081:80"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: "http://localhost:8081"

      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: queuenow
      DB_USERNAME: root
      DB_PASSWORD: root

      # Google OAuth (isi sendiri)
      GOOGLE_CLIENT_ID: ""
      GOOGLE_CLIENT_SECRET: ""
      GOOGLE_REDIRECT_URL: "http://localhost:8081/auth/google/callback"

      # Midtrans (isi sendiri)
      MIDTRANS_IS_PRODUCTION: "false"
      MIDTRANS_SERVER_KEY: ""
      MIDTRANS_CLIENT_KEY: ""
      MIDTRANS_PRO_PRICE: "25000"
      MIDTRANS_PRO_NAME: "QueueNow Pro"

      # WAJIB Laravel (isi APP_KEY hasil generate)
      APP_KEY: ""
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: queuenow_db
    environment:
      MYSQL_DATABASE: queuenow
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - queuenow_mysql:/var/lib/mysql

volumes:
  queuenow_mysql:
