services:
  app:
    image: kacangbiasa/queuenow-app:latest
    container_name: queuenow_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: queuenow
      DB_USERNAME: root
      DB_PASSWORD: root

  web:
    image: kacangbiasa/queuenow-web:latest
    container_name: queuenow_web
    ports:
      - "8000:80"
    depends_on:
      - app

  db:
    image: mysql:8
    container_name: queuenow_db
    environment:
      MYSQL_DATABASE: queuenow
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  db_data:
