version: "3.8"

services:
  app:
    build: .
    container_name: queuenow_app
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      APP_NAME: QueueNow
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000

      LOG_CHANNEL: stderr

      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: queuenow
      DB_USERNAME: root
      DB_PASSWORD: root

  web:
    image: nginx:alpine
    container_name: queuenow_web
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8
    container_name: queuenow_db
    environment:
      MYSQL_DATABASE: queuenow
      MYSQL_ROOT_PASSWORD: root